version: '3'

services:

  db:
    image: mongo:4.0
    restart: always
    # volumes:
    #    - .db:/data/db 
    ports:
      - 27017:27017
    # depends_on:
    #   - requerimientos
    # networks:
    #   - custom
  python:
    container_name: cont_dos
    build: "./cont_dos"
    #command: pip install -r requerimientos.txt
    depends_on: 
      - db

  flask:
    container_name: cont_tres
    build: "./cont_tres"
    environment: 
      - "FLASK_APP=view.py"
    ports: 
      - 5000:5000
    
    depends_on: 
      - python
      

  

  